// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor;

namespace Servidor.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Servidor.Models.Article", b =>
                {
                    b.Property<int>("Id_Article")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Article_Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_RefMuseum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isDamaged")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Article");

                    b.HasIndex("Id_RefMuseum");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Servidor.Models.Museum", b =>
                {
                    b.Property<int>("Id_Museum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Museum_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Museum");

                    b.ToTable("Museum");
                });

            modelBuilder.Entity("Servidor.Models.Article", b =>
                {
                    b.HasOne("Servidor.Models.Museum", "Museum")
                        .WithMany("Articles")
                        .HasForeignKey("Id_RefMuseum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("Servidor.Models.Museum", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
